### ISSUE TITLE
Can not relocate cursor with the mouse when editing a tile

### ISSUE THREAD

**Issue by rnunez80** [castlecms/castle.cms#6] opened 2017-01-11 20:05 UTC
When you select a tile to edit you can not select content of the tile with the mouse or click to get the cursor to a lower position in the tile. You have to use the keyboard to get around the tile which work fine for small tiles but not long tiles with a lot of text.

**Comment by vangheem** [comment] 2017-01-11 20:08
Could you possibly do a video? This does not happen to me. Also, this issue might belong to plone.app.mosaic.

**Comment by rnunez80** [comment] 2017-01-12 12:22
The misbehavior happens when you have a calendar tile on the page.
[Tile misbehavior Video](https://demo-cuny.castlecms.io/video-repository/quickcast-12-01-2017-07-16-11.mp4/view)

**Comment by vangheem** [comment] 2017-01-12 15:59
Very odd. I can reproduce this. It *only* happens after the calendar tile is dropped.

**Comment by vangheem** [comment] 2017-01-12 16:03
@RobZoneNet can you poke around and see if there is CSS bug going on here preventing focus from the calendar tile?

**Comment by vangheem** [comment] 2017-02-01 23:33
Turns out the problem originates from an incompatibilities with jquery.event.drag that mockup is using.

I've been fiddling with it and it's complicated...

Options are to hack jquery.event.drag to work with it or switch to https://github.com/Serhioromano/bootstrap-calendar maybe.

**Comment by vangheem** [comment] 2017-02-02 14:04
Fixed with https://github.com/plone/mockup/pull/733 and rebuilt bundle in castle, committed.

**Closed by vangheem** 2017-02-02 14:04 UTC
